# Main Code Scanner that calls other worflow scanners
name: CodeScan

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '38 18 * * 1'
env:
  LANGS: javascript, python

jobs:
  #####
  #  Check TF files with TFsec-sarif tool
  #####
  step1-tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: generate tfsec output
        id: generate-tfsec-output
        run: echo "::set-output name=step1-output::false"
    outputs:
      tfsec-output: ${{ steps.generate-tfsec-output.outputs.step1-output }}
  tfsec-run:
    needs: step1-tfsec
    if: ${{ needs.step1-tfsec.outputs.tfsec-output == 'true' }}  
    uses: yicheung/Terraform/.github/workflows/tfsec-sarif.yml@v1.0
  #####
  #  Check CodeQL
  #####
  step2-codeql:
    runs-on: ubuntu-latest
    steps:
      - name: generate codeql output
        id: generate-codeql-output
        run: echo "::set-output name=step2-output::true"
      - name: output languages
        id: generate-codeql-langs
        run: echo "::set-output name=step2-langs::${{ env.LANGS }}"  
    outputs:
      codeql-output: ${{ steps.generate-codeql-output.outputs.step2-output }}
      langs: ${{ steps.generate-codeql-langs.outputs.step2-langs }}
  codesql-run:
    name: Execute CodeSQL
    runs-on: ubuntu-latest   
    needs: step2-codeql 
    if: ${{ needs.step2-codeql.outputs.codeql-output == 'true' }}
    steps:
      - name: test uses 
        run: echo "LANGS ${{ env.LANGS }}"            
      - name: test uses 
        run: echo "Jobs langs ${{ steps.step2-codeql.outputs.langs }}"      
        


